### ISSUE TITLE
Open Question: Schema for geneset objects

### ISSUE THREAD

**Issue by ravila4** [biothings/mygeneset.info#13]
This is for discussing the general structure of the schema and naming convention of the fields. As we add more data sources, we may find that we need to modify certain aspects of the model.
This is what what my current model looks like in YAML-like format:

```yaml
_id: string
  is_public: boolean
  author: string       # Only for user-created datasets
  date: string         # Only for user-created datasets
  taxid: integer
  genes:
    - mygene_id: string      # mygene.info primary key
      uniprot: string or list         # Can be empty
      ncbigene: string or list        # Can be empty
      ensemblgene: string or list     # Can be empty
      symbol: string
      name: string                    # Can be empty
  [source_name]:           # Only for public genesets
    id: string             # Usually same as _id, unless _id contains id+taxid
    [source_specific_data]
```

For example, for a GO geneset:

```
{
  "_id": "GO:0007288_9606",
  "is_public": true,
  "taxid": "9606",
  "genes": [
    {
      "mygene_id": "286207"
      "uniprot": "Q5JU67",
      "symbol": "CFAP157",
      "ncbigene": "286207"
      "ensemblgene": "ENSG00000160401"
      "name": "cilia and flagella associated protein 157"
    },
    {
      "mygene_id": "79846"
      "uniprot": "A5D8W1",
      "symbol": "CFAP69",
      "ncbigene": "79846"
      "ensemblgene": "ENSG00000105792"
      "name": "cilia and flagella associated protein 69"
    },
  ],
  "go": {
    "id": "GO:0007288",
    "name": "sperm axoneme assembly",
    "type": "biological_process",
    "description": "The assembly and organization of the sperm flagellar axoneme, the bundle of microtubules and associated proteins that forms the core of the eukaryotic sperm flagellum, and is responsible for movement. [GOC:bf, GOC:cilia, ISBN:0198547684]"
  }
}
```

**Comment by ravila4** [comment]
Question: Should we produce Uniprot IDs for datasets that do not specify them? (e.g. GO data has Uniprot IDs, but wikipathways comes with NCBI ids.)
Mapping from UniProt to gene is often 1:1 , but the reverse is usually 1:many. Furthermore, UniProt often comes with two sets of IDs: SwissProt and TrEMBL: https://www.uniprot.org/help/uniprotkb_sections

**Comment by dongbohu** [comment]
@ravila4: One question on `source_name`: so this field's name will vary depending on the exact data source? I was thinking of something like this:
```
source:
    id: str
    name: str
    description: str
    ...
```
So in your example, it will become:
```
...
"source": {
    "id": "GO:0007288",
    "name": "sperm axoneme assembly",
    "type": "biological_process",
    "description": "The assembly and organization of ..."
}
...
```

**Comment by ravila4** [comment]
@dongbohu  If we use the same field name, then all its sub-fields would be merged during the build process. I think keeping them separate allows us to ask something like: "Give me all the public genesets that come from GO".

**Comment by dongbohu** [comment]
@ravila4 Thank you for your reply. I am not familiar with the ElasticSearch-based API. What will be the syntax to get all GO public genesets? Something like `.../query?go=*`?

**Comment by ravila4** [comment]
@dongbohu I believe it would be: `.../query?q=go*`

**Comment by dongbohu** [comment]
Good to know. Thanks!

**Comment by ravila4** [comment]
@dongbohu  Correction: It would be `/query?q=_exists_:go` Learning about this too...
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax

**Comment by dongbohu** [comment]
💯  Thanks again!

**Comment by dongbohu** [comment]
@ravila4: I have been thinking of a better way to deal with the genes that are not found by mygene.info. A missed gene will look like this in the current schema:
```
...
genes: [
  {
    "mygene_id": null
    "uniprot": null
    "symbol": null,
    "ncbigene": null
    "ensemblgene": null
    "name": null
  },
  ...
]
```
which is a waste of bandwidth (and boring). Can we change it into:
```
...
genes: [
  {
    "source": <original_gene_name_in_data_source>
    "mygeneinfo": null
  },
  ...
]
```
in which `<original_gene_name_in_data_source>` is the original gene ID in data source (which is the query string that we use to search in mygene.info).

And a gene that is found in mygene.info would look like this:
```
"genes": [
  {
    "source": <original_gene_name_in_data_source>
    "mygeneinfo": {
      "_id": "286207"
      "uniprot": "Q5JU67",
      "symbol": "CFAP157",
      "ncbigene": "286207"
      "ensemblgene": "ENSG00000160401"
      "name": "cilia and flagella associated protein 157"
    },
  },
 ...
]

**Comment by ravila4** [comment]
@dongbohu  I can see value in keeping the original source tag, for example KEGG's 'locus_tag', which is not in the current schema... but we also want to standardize the fields returned by the "mygeneinfo" object, otherwise the mapping will include all possible identifiers supported by mygene.info...

I think perhaps something like:

```yaml
"genes": [
   { 
     "source": {
       "identifier": <original_id_name e.g. 'locus_tag'>
       "value": <original value>
     }
    # MyGene.info ids
    "_id": "286207"
    "uniprot": "Q5JU67",
    "symbol": "CFAP157",
    "ncbigene": "286207"
    "ensemblgene": "ENSG00000160401"
    "name": "cilia and flagella associated protein 157"
  },
...
]
```

Also, we normally don't store any null values in the data. (You can use biothings.utils.dataload.dict_sweep() to drop them).
If we don't find a gene in mygene.info, we should simply exclude the fields, but perhaps add a tag? There should be an easy, on-the-fly way to filter out genes that were not found.

```yaml
"source": {
       "identifier": <original_id_name e.g. 'locus_tag'>
       "value": <original value>
       "not_found": True
     }
```
Additionally, if we find conflicting information between mygene.info and the source, we should also correct it. For example, if a source NCBI id is retired or deprecated, we may add a flag:

```yaml
"genes": [
   { 
     "source": {
       "identifier": "ncbigene",
       "value": "100128403".
       "retired": "True"
     }
    # MyGene.info ids
    "_id": "9899"
    "uniprot": "Q7L1I2",
    "symbol": "SV2B",
    "ncbigene": "9899"
    "ensemblgene": "ENSG00000160401"
    "name": "synaptic vesicle glycoprotein 2B"
  },
...
]
```
Let me know what you think.

---
Tagging @newgene for input.
